# Generated by Django 4.2.6 on 2024-05-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bibtext",
            name="index",
            field=models.FloatField(null=True),
        ),
    ]
