# Generated by Django 4.2.6 on 2024-05-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_bibtext_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="bibtext",
            name="points",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="bibtext",
            name="index",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
