# Generated by Django 4.2.6 on 2024-05-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_remove_bibtext_points_remove_scientist_ball"),
    ]

    operations = [
        migrations.CreateModel(
            name="points",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255, unique=True)),
                ("points", models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
