# Generated by Django 4.2.6 on 2024-05-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_points"),
    ]

    operations = [
        migrations.DeleteModel(
            name="points",
        ),
        migrations.AddField(
            model_name="bibtext",
            name="ball",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
